root = "."
testdata_dir = ".testdata"
tmp_dir = ".tmp"

[build]
bin = "./.tmp/main"
cmd = "templ generate && go build -o .tmp/main ."
args_bin = ["--prod false"]
delay = 1000
exclude_dir = ["assets", ".tmp", "vendor", ".testdata", "node_modules"]
exclude_file = ["styles.css", "styles.min.css"]
exclude_regex = [".*_test.go", ".*_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "templ", "html"]
log = "build-errors.log"
send_interrupt = true
kill_delay = 1000
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = true

[misc]
clean_on_exit = true

# [screen]
# clear_on_rebuild = true
