// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "shitty-portfolio/internal/views/base"

func Hello() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = base.Sidebar().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" <div class=\"bg-surface\"><div class=\"flex flex-row px-10 py-5\"><div class=\"flex-1 text-left flex flex-col justify-start items-start gap-2\"><p class=\"mt-3 text-6xl text-primary font-extrabold\">ItsKhanh</p><p class=\"text-base italic text-primary\">knguyen.66</p><p class=\"mt-3 text-base text-secondary\">Backend, DevOps, AI and chasing trends</p><!-- <div class=\"mt-3\">\n\t\t\t\t\t\t<a href=\"#\" class=\"inline-flex items-center rounded border px-8 py-3 bg-indigo-500 text-white\">\n\t\t\t\t\t\t\t<span class=\"text-sm font-medium\">Learn more</span>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t\t<a href=\"#\" class=\"inline-flex items-center rounded border px-8 py-3\">\n\t\t\t\t\t\t\t<span class=\"text-sm font-medium\">Learn more</span>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</div> --><span class=\"w-full flex items-center pr-3 py-3\"><span class=\"h-px flex-1 bg-stone-500\"></span> <span class=\"px-6 text-sm text-secondary\">This is not me, apparently --> </span></span><p class=\"mt-5 text-base\"></p></div><div class=\"flex-1 my-4\"><img class=\"w-full object-cover\" src=\"https://images.unsplash.com/photo-1724269964916-0b4e11542083?q=80&amp;w=2070&amp;auto=format&amp;fit=crop&amp;ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D\"></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = base.Index().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
